### PR TITLE
.append() issue #32

### PR DESCRIPTION
**Pull request by jonmelcher**
in .append() use DocumentFragment to insert text instead of altering the innerHTML
unit test to verify that the issue has been addressed

### CODE REVIEW

**Comment by itsrachelfish** [comment]
S-someone actually uses my software?????? Whhhhaaaaat??????

weeb gif

**Comment by itsrachelfish** [comment]
@jonmelcher Thank you so much for your contribution! Unfortunately it looks like the DocumentFragment constructor isn't supported yet in PhantomJS, so tests fail when running gulp:

```
[07:51:04] Testing test-page.html
[07:51:04] Test failed: Appending strings and elements
[07:51:04] Failed assertion: Died on test #1 global code@file:////home/rachel/Projects/basic/test/append.js:1:11: DocumentFragmentConstructor is not a constructor (evaluating 'new DocumentFragment()')
[07:51:04] file:////home/rachel/Projects/basic/dist/basic.js:224:45
[07:51:04] forEach@file:////home/rachel/Projects/basic/dist/basic.js:36:26
[07:51:04] append@file:////home/rachel/Projects/basic/dist/basic.js:217:21
[07:51:04] file:////home/rachel/Projects/basic/test/append.js:13:24
[07:51:04] 
[07:51:04] Took 8ms to run 17 tests. 16 passed, 1 failed.
[07:51:04] gulp-qunit: ✖ QUnit assertions failed in test-page.html
```

Also, by using textContent, it is no longer possible to append HTML strings to the page.

**Comment by jonmelcher** [comment]
Sure thing!  That's strange that the tests were failing, they were passing on my local branch :(.  I noticed that HTML strings were no longer able to be appended but it slipped my mind that this would be a regression.  I'll spend some more time with it and hopefully have a proper contribution soon!

**Comment by itsrachelfish** [comment]
The tests passed for me in Firefox, but not in gulp. I've actually already found a solution and was planning on merging this because I liked your tests so much...

**Comment by itsrachelfish** [comment]
@jonmelcher It's definitely not as pretty as what you had originally, but it works:
https://github.com/wetfish/basic/blob/master/src/append.js#L16-L19

I also updated the tests to actually make sure the content was appended.
https://github.com/wetfish/basic/blob/master/test/append.js

If you'd like to make the same updates to .prepend() I would be happy to merge it! :sparkling_heart:

**Comment by itsrachelfish** [comment]
Also, if you could think of a way to actually test if an HTML string was appended as HTML, that would be great too! Right now the HTML could be appended as a string and it would still pass the test.

**Pull request merged**
